### ISSUE TITLE
TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by andrucz** [ktalebian/typescript-compile-error-formatter#5]
`decomposeIssue` might return issues without location:
https://github.com/ktalebian/typescript-compile-error-formatter/blob/d43d4555048c725e678bbd79fd641b777f86fcf4/src/index.ts#L39

`formatter` assumes issues always have a location:
https://github.com/ktalebian/typescript-compile-error-formatter/blob/d43d4555048c725e678bbd79fd641b777f86fcf4/src/index.ts#L55

I'm getting this error when trying to run a plugin using Flex v2:
```
TypeError: Cannot read property 'start' of undefined
    at Object.formatter [as default] (C:\Users\andru\.twilio-cli\node_modules\@k88\typescript-compile-error-formatter\dist\index.js:41:23)
    at format (C:\Users\andru\.twilio-cli\node_modules\flex-plugin-webpack\dist\compiler.js:105:120)
    at Array.map (<anonymous>)
    at C:\Users\andru\.twilio-cli\node_modules\flex-plugin-webpack\dist\compiler.js:108:101
    at SyncHook.eval [as call] (eval at create (C:\Users\andru\.twilio-cli\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)    
    at SyncHook.lazyCompileHook (C:\Users\andru\.twilio-cli\node_modules\tapable\lib\Hook.js:154:20)
    at ForkTsCheckerWebpackPlugin.handleServiceMessage (C:\Users\andru\.twilio-cli\node_modules\fork-ts-checker-webpack-plugin\lib\index.js:402:36)
    at C:\Users\andru\.twilio-cli\node_modules\fork-ts-checker-webpack-plugin\lib\index.js:255:35
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by ktalebian** [comment]
@andrucz is there a way to replicate this? An `issue` should _always_ have a location.

**Comment by andrucz** [comment]
@ktalebian that occurs whenever there's a compilation error in a Flex v2 plugin.
I'm using typescript@4.5.5.

I've inspected the value received by the formatter function and it looks like this:

```
{
  origin: 'typescript',
  code: '2339',
  severity: 'error',
  message: "Property 'onChangePage' does not exist on type '{ page: number; rowsPerPage: number; onPageChange: (_: any, newPage: number) => void; onChangeRowsPerPage: (event: ChangeEvent<HTMLInputElement>) => void; }'.",
  file: 'C:/Users/.../plugin-voicemail/src/components/Voicemail/ListPage/Table/VoicemailsTable.tsx',
  line: 65,
  character: 30
}
```

**Comment by andrucz** [comment]
@ktalebian and I see these warnings when I run `twilio plugins:install @twilio-labs/plugin-flex`:

```
warning @twilio-labs/plugin-flex@4.3.1: The engine "@twilio/cli-core" appears to be invalid.
warning @twilio-labs/plugin-flex@4.3.1: The engine "twilio-cli" appears to be invalid.
warning "@twilio-labs/plugin-flex > flex-dev-utils > axios-cache-adapter@2.7.3" has incorrect peer dependency "axios@~0.21.1".
warning "@twilio-labs/plugin-flex > flex-plugin-scripts > flex-plugin-webpack > @k88/typescript-compile-error-formatter@2.1.0" has incorrect peer dependency "fork-ts-checker-webpack-plugin@^6".
```

I'm using twilio-cli@2.36.1

**Comment by ktalebian** [comment]
@andrucz the new version of the CLI should be fixed now.
